---
title: "Supplementary information"
output:
  html_document:
    df_print: paged
    fig_caption: yes
  pdf_document: default
---
  

```{r load data ,echo=FALSE,message=FALSE,warning=FALSE}
load("~/projects/cdk1_cyclinB1/phase_separation/disorder/disoWS.RData")

```

```{r setup,echo=FALSE,message=FALSE,warning=FALSE,prompt=FALSE}
library(jsonlite)
library(readr)
library(ggplot2)
library(GGally)
library(vcd)
library(kableExtra)
library(ggpubr)
library(Rcpi)
library(Biostrings)
library(eulerr)

# #################################
# ########### FUCNTIONS ###########
# #################################
# 
# #__________Spot disorder__________
# 
# 
# getSpotDisoMatrix <- function(disoPath){ 
#   output_list <- list()
#   for (disoFile in dir(path = disoPath,pattern = "*.spotd")) {
#     id=strsplit(disoFile,split = "\\.")[[1]][1]
#     # print(id)
#     # print(paste(disoPath,disoFile,sep = ""))
#     auxdf <- read.delim(paste(disoPath,disoFile,sep = ""), header=FALSE, comment.char="#")
#     disoRunningLenghts <- rle(as.vector(auxdf$V4))
#     start=1
#     disoMatrix <- matrix(ncol = 4,nrow = length(disoRunningLenghts$lengths))
#     for (i in 1:length(disoRunningLenghts$lengths)) {
#       end=start+disoRunningLenghts$lengths[i]-1
#       disoMatrix[i,] <- as.character(c(start,end,disoRunningLenghts$values[i],disoRunningLenghts$lengths[i]))
#       # print(c(start,end,test$values[i],test$lengths[i]))
#       start=end+1
#     }
#     output_list[[id]] <- disoMatrix
#   }
#   # print(disoMatrix)
#   # print(which(targetDf$acc==id))
#   return(output_list)
# }
# #__________other functions__________
# 
# # yeastDiso is a complex database from MobiDB Saccharomyces cerevisiae. 
# 
# #################################
# ############# DATA ##############
# #################################
# 
# yeastDiso<-stream_in(con = file("~/projects/cdk1_cyclinB1/phase_separation/disorder/disorder_UP000002311.mjson"),verbose = F)
# yeastDiso$mobidb_consensus <- yeastDiso$mobidb_consensus$disorder
# colnames(yeastDiso)[5] <- "disorder"
# 
# CDK1targetSacCer <- read_delim("~/projects/cdk1_cyclinB1/phase_separation/disorder/CDK1targetSacCer.csv", 
#                           "\t", quote = "\\\"", escape_double = FALSE, 
#                           col_types = cols(X1 = col_skip(), input = col_skip(), 
#                           `yourlist:M201907046746803381A1F0E0DB47453E0216320D4B0BD1N` = col_skip()), 
#                           trim_ws = TRUE)
# 
# # Now the comumn "disorder" is a unnamed list with a complex structure for each row of the data frame
# 
# 
# spotDisorderList <- getSpotDisoMatrix("/home/gdubra/projects/cdk1_cyclinB1/phase_separation/disorder/spot_run_yeast/")

# load("~/projects/cdk1_cyclinB1/phase_separation/disorder/disoWS.RData")
```
  
## Supplementary Figure 6  
  

```{r scores ,echo=FALSE,message=FALSE,warning=FALSE, fig.cap="Supplementary Figure 6 A: Comparision of the dependance of the phosphorylation on the on the ammount of protein" }

PhosVsPL<-ggplot(scoresData,aes(x=log10(`Protein Level`),y=log10(Phosphorylation)))+geom_point(aes(color=target)) + theme_linedraw() + xlab("Log10(Protein Level<ng>)") + ylab("Log10(Phosphorylation)")
PhosVsnM<-ggplot(scoresData,aes(x=log10(`nmol`),y=log10(Phosphorylation)))+geom_point(aes(color=target)) + theme_linedraw() + theme(axis.title.y = element_blank())+ xlab("Log10(nmoles)") + ylab("Log10(Phosphorylation)")
PhosVsnEqSTP<-ggplot(scoresData,aes(x=log10(`nEq_STP`),y=log10(Phosphorylation)))+geom_point(aes(color=target)) + theme_linedraw()  + xlab("Log10(nEquivalents S/T-P)") + ylab("Log10(Phosphorylation)") 
PhosVsnEqSTPXKR<-ggplot(scoresData,aes(x=log10(`nEq_STPXKR`),y=log10(Phosphorylation)))+geom_point(aes(color=target)) + theme_linedraw() + theme(axis.title.y = element_blank()) + xlab("Log10(nEquivalents S/T-P-x-K/R)") + ylab("Log10(Phosphorylation)")

ggarrange(PhosVsPL,PhosVsnM,PhosVsnEqSTP,PhosVsnEqSTPXKR,common.legend = TRUE, legend = "bottom")
```

```{r  ,echo=FALSE,message=FALSE,warning=FALSE, fig.cap="Supplementary Figure 6 B:",fig.width=12}

ps_pm <- ggplot(scoresData,aes(y=`P-Score`,x=log10(Phosphorylation/nmol)))+geom_point(aes(color=target)) + theme_linedraw()  +  ylab("P-Score") + xlab("Log10(Phosphorylation/nMoles)")

ps_pes <- ggplot(scoresData,aes(y=`P-Score`,x=log10(Phosphorylation/nEq_STP)))+geom_point(aes(color=target)) + theme_linedraw() + theme(axis.title.y = element_blank()) +  ylab("P-Score") + xlab("Log10(Phosphorylation/nEquivalents S/T-P)")

ps_pef <- ggplot(scoresData,aes(y=`P-Score`,x=log10(Phosphorylation/nEq_STPXKR)))+geom_point(aes(color=target)) + theme_linedraw() + theme(axis.title.y = element_blank()) +  ylab("P-Score") + xlab("Log10(Phosphorylation/nEquivalents S/T-P-x-K/R)")

ggarrange(ps_pm,ps_pes,ps_pef,nrow = 1, ncol = 3,common.legend = TRUE, legend = "bottom")
```
```{r  ,echo=FALSE,message=FALSE,warning=FALSE, fig.cap="Figure 9:",fig.height=10}


# compDataSet$levelPhosphoRes<-cut(compDataSet$percPhosphoRes,breaks = c(0,0.45,1,10),labels = c("Low","Mid","High"))
# 
# ggplot(subset(CDK1targetSacCer,`P-Score`>0),aes(x=`P-Score`,y=`[ST]-P-X-[KR]`/length))+geom_point(aes(color=target))+geom_smooth(method=lm, se=FALSE)


```
  
## Supplementary Figure   
  
```{r Holt disorder percentage all,echo=FALSE,message=FALSE,warning=FALSE,fig.cap=""}


dens_simpleDisoPerc<-ggplot(Holt_data)+geom_density(aes(x = predDisoPerc,fill = target_all),alpha=.5,bw=5)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + scale_y_continuous(limits = c(0,0.05)) + scale_x_continuous(name="% of predicted Disorder",limits = c(0,100))+ggtitle("Simple Predictor")
dens_liteDisoPerc<-ggplot(subset(Holt_data,!is.na(predLiteDisoPerc)))+geom_density(aes(x = predLiteDisoPerc,fill = target_all),alpha=.5,bw=5)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + theme(axis.title.y = element_blank())+ scale_y_continuous(limits = c(0,0.05)) + scale_x_continuous(name="% of predicted Disorder",limits = c(0,100)) + theme(axis.title.y = element_blank())+labs(title="MobiDB-Lite Predictor")
dens_spotDisoPerc<-ggplot(Holt_data)+geom_density(aes(x = predSpotDisoPerc,fill = target_all),alpha=.5,bw=5)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + theme(axis.title.y = element_blank())+ scale_y_continuous(limits = c(0,0.05)) + scale_x_continuous(name="% of predicted Disorder",limits = c(0,100)) + theme(axis.title.y = element_blank())+labs(title="SPOT Predictor")

hist_simpleDisoPerc<-ggplot(Holt_data)+geom_histogram(aes(x = predDisoPerc,fill = target_all),alpha=.5,bins = 50)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5))  + scale_x_continuous(name="% of predicted Disorder",limits = c(-2,102))
hist_liteDisoPerc<-ggplot(subset(Holt_data,!is.na(predLiteDisoPerc)))+geom_histogram(aes(x = predLiteDisoPerc,fill = target_all),alpha=.5,bins = 50)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5))  + theme(axis.title.y = element_blank())+  scale_x_continuous(name="% of predicted Disorder",limits = c(-2,102)) + theme(axis.title.y = element_blank())
hist_spotDisoPerc<-ggplot(Holt_data)+geom_histogram(aes(x = predSpotDisoPerc,fill = target_all),alpha=.5,bins = 50)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + theme(axis.title.y = element_blank())+ scale_x_continuous(name="% of predicted Disorder",limits = c(-2,102)) + theme(axis.title.y = element_blank())

ggarrange(dens_simpleDisoPerc,dens_liteDisoPerc,dens_spotDisoPerc,hist_simpleDisoPerc,hist_liteDisoPerc,hist_spotDisoPerc,nrow = 2, ncol = 3,common.legend = TRUE,legend = "bottom", align = "hv")


holt_all_simple_NonCdk1_VAR <- var(Holt_data$predDisoPerc[Holt_data$target_all=="Non Cdk1 target"],na.rm = T)
holt_all_simple_Cdk1_VAR <- var(Holt_data$predDisoPerc[Holt_data$target_all=="Cdk1 target"],na.rm = T)
holt_all_simple_Cdk1_SD <- sd(Holt_data$predDisoPerc[Holt_data$target_all=="Cdk1 target"],na.rm = T)
holt_all_simple_NonCdk1_SD <- sd(Holt_data$predDisoPerc[Holt_data$target_all=="Non Cdk1 target"],na.rm = T)
holt_all_simple_test <- t.test(Holt_data$predDisoPerc[Holt_data$target_all=="Cdk1 target"],Holt_data$predSpotDisoPerc[Holt_data$target_all=="Non Cdk1 target"],var.equal=T)

holt_all_lite_NonCdk1_VAR <- var(Holt_data$predLiteDisoPerc[Holt_data$target_all=="Non Cdk1 target"],na.rm = T)
holt_all_lite_Cdk1_VAR <- var(Holt_data$predLiteDisoPerc[Holt_data$target_all=="Cdk1 target"],na.rm = T)
holt_all_lite_Cdk1_SD <- sd(Holt_data$predLiteDisoPerc[Holt_data$target_all=="Cdk1 target"],na.rm = T)
holt_all_lite_NonCdk1_SD <- sd(Holt_data$predLiteDisoPerc[Holt_data$target_all=="Non Cdk1 target"],na.rm = T)
holt_all_lite_test <- t.test(Holt_data$predLiteDisoPerc[Holt_data$target_all=="Cdk1 target"],Holt_data$predSpotDisoPerc[Holt_data$target_all=="Non Cdk1 target"],var.equal=T)

holt_all_spot_NonCdk1_VAR <- var(Holt_data$predSpotDisoPerc[Holt_data$target_all=="Non Cdk1 target"])
holt_all_spot_Cdk1_VAR <- var(Holt_data$predSpotDisoPerc[Holt_data$target_all=="Cdk1 target"],na.rm = T)
holt_all_spot_Cdk1_SD <- sd(Holt_data$predSpotDisoPerc[Holt_data$target_all=="Cdk1 target"],na.rm = T)
holt_all_spot_NonCdk1_SD <- sd(Holt_data$predSpotDisoPerc[Holt_data$target_all=="Non Cdk1 target"],na.rm = T)
holt_all_spot_test <- t.test(Holt_data$predSpotDisoPerc[Holt_data$target_all=="Cdk1 target"],Holt_data$predSpotDisoPerc[Holt_data$target_all=="Non Cdk1 target"],var.equal=T)
```

```{r consensus phosphosites in disorder,echo=FALSE,message=FALSE,warning=FALSE,fig.cap=""}
#Ubersax

UbersaxFullconsPlot <- ggplot(Ubersax_data) + geom_density(aes(x = (`[ST]-P-X-[KR]`/length)*100,fill = target),alpha=.5,bw=0.2)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + scale_y_continuous(limits = c(0,2)) + scale_x_continuous(name="Number of phosphosites per 100 residues",limits = c(0,3))+ggtitle("[ST]-P-X-[KR]")
UbersaxMinimalconsPlot <- ggplot(Ubersax_data) + geom_density(aes(x = (`[ST]-P`/length)*100,fill = target),alpha=.5,bw=0.2)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + scale_y_continuous(limits = c(0,2)) + scale_x_continuous(name="Number of phosphosites per 100 residues",limits = c(0,3))+ggtitle("[ST]-P")

ggarrange(UbersaxFullconsPlot,UbersaxMinimalconsPlot,nrow = 1, ncol = 2,common.legend = TRUE,legend = "bottom", align = "hv")


ubersax_full_NonCdk1_VAR <- var((Ubersax_data$`[ST]-P-X-[KR]`[Ubersax_data$target=="Non Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Non Cdk1 target"])*100,na.rm = T)
ubersax_full_Cdk1_VAR <- var((Ubersax_data$`[ST]-P-X-[KR]`[Ubersax_data$target=="Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Cdk1 target"])*100,na.rm = T)
ubersax_full_Cdk1_SD <- sd((Ubersax_data$`[ST]-P-X-[KR]`[Ubersax_data$target=="Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Cdk1 target"])*100,na.rm = T)
ubersax_full_NonCdk1_SD <- sd((Ubersax_data$`[ST]-P-X-[KR]`[Ubersax_data$target=="Non Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Non Cdk1 target"])*100,na.rm = T)
ubersax_full_test <- t.test((Ubersax_data$`[ST]-P-X-[KR]`[Ubersax_data$target=="Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Cdk1 target"])*100,(Ubersax_data$`[ST]-P-X-[KR]`[Ubersax_data$target=="Non Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Non Cdk1 target"])*100,var.equal=T)

ubersax_minimal_NonCdk1_VAR <- var((Ubersax_data$`[ST]-P`[Ubersax_data$target=="Non Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Non Cdk1 target"])*100,na.rm = T)
ubersax_minimal_Cdk1_VAR <- var((Ubersax_data$`[ST]-P`[Ubersax_data$target=="Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Cdk1 target"])*100,na.rm = T)
ubersax_minimal_Cdk1_SD <- sd((Ubersax_data$`[ST]-P`[Ubersax_data$target=="Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Cdk1 target"])*100,na.rm = T)
ubersax_minimal_NonCdk1_SD <- sd((Ubersax_data$`[ST]-P`[Ubersax_data$target=="Non Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Non Cdk1 target"])*100,na.rm = T)
ubersax_minimal_test <- t.test((Ubersax_data$`[ST]-P`[Ubersax_data$target=="Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Cdk1 target"])*100,(Ubersax_data$`[ST]-P`[Ubersax_data$target=="Non Cdk1 target"]/Ubersax_data$length[Ubersax_data$target=="Non Cdk1 target"])*100,var.equal=T)

#Holt

HoltMinCons <- sapply(Holt_data$sequence,function(x){index<-unlist(gregexpr("[ST]P",x),use.names = F)
                                                      if (index[1]==-1) {return(0)
                                                      } else {return(length(index))}})
names(HoltMinCons) <- NULL 
HoltFullCons <- sapply(Holt_data$sequence,function(x){index<-unlist(gregexpr("[ST]P.[KR]",x),use.names = F)
                                                      if (index[1]==-1) {return(0)
                                                      } else {return(length(index))}})
names(HoltFullCons) <- NULL 

Holt_data$`[ST]-P-X-[KR]`<-HoltFullCons
Holt_data$`[ST]-P`<-HoltMinCons


HoltFullconsPlot <- ggplot(Holt_data) + geom_density(aes(x = (`[ST]-P-X-[KR]`/length)*100,fill = target_all),alpha=.5,bw=0.2)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + scale_y_continuous(limits = c(0,2)) + scale_x_continuous(name="Number of phosphosites per 100 residues",limits = c(0,3))+ggtitle("[ST]-P-X-[KR]")
HoltMinimalconsPlot <- ggplot(Holt_data) + geom_density(aes(x = (`[ST]-P`/length)*100,fill = target_all),alpha=.5,bw=0.2)+ theme_linedraw()+theme(plot.title = element_text(hjust = 0.5)) + scale_y_continuous(limits = c(0,2)) + scale_x_continuous(name="Number of phosphosites per 100 residues",limits = c(0,3))+ggtitle("[ST]-P")

ggarrange(HoltFullconsPlot,HoltMinimalconsPlot,nrow = 1, ncol = 2,common.legend = TRUE,legend = "bottom", align = "hv")


Holt_full_NonCdk1_VAR <- var((Holt_data$`[ST]-P-X-[KR]`[Holt_data$target_all=="Non Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Non Cdk1 target"])*100,na.rm = T)
Holt_full_Cdk1_VAR <- var((Holt_data$`[ST]-P-X-[KR]`[Holt_data$target_all=="Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Cdk1 target"])*100,na.rm = T)
Holt_full_Cdk1_SD <- sd((Holt_data$`[ST]-P-X-[KR]`[Holt_data$target_all=="Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Cdk1 target"])*100,na.rm = T)
Holt_full_NonCdk1_SD <- sd((Holt_data$`[ST]-P-X-[KR]`[Holt_data$target_all=="Non Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Non Cdk1 target"])*100,na.rm = T)
Holt_full_test <- t.test((Holt_data$`[ST]-P-X-[KR]`[Holt_data$target_all=="Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Cdk1 target"])*100,(Holt_data$`[ST]-P-X-[KR]`[Holt_data$target_all=="Non Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Non Cdk1 target"])*100,var.equal=T)

Holt_minimal_NonCdk1_VAR <- var((Holt_data$`[ST]-P`[Holt_data$target_all=="Non Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Non Cdk1 target"])*100,na.rm = T)
Holt_minimal_Cdk1_VAR <- var((Holt_data$`[ST]-P`[Holt_data$target_all=="Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Cdk1 target"])*100,na.rm = T)
Holt_minimal_Cdk1_SD <- sd((Holt_data$`[ST]-P`[Holt_data$target_all=="Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Cdk1 target"])*100,na.rm = T)
Holt_minimal_NonCdk1_SD <- sd((Holt_data$`[ST]-P`[Holt_data$target_all=="Non Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Non Cdk1 target"])*100,na.rm = T)
Holt_minimal_test <- t.test((Holt_data$`[ST]-P`[Holt_data$target_all=="Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Cdk1 target"])*100,(Holt_data$`[ST]-P`[Holt_data$target_all=="Non Cdk1 target"]/Holt_data$length[Holt_data$target_all=="Non Cdk1 target"])*100,var.equal=T)


```